Repository replicatedhq/kots.io, pull requests merged in 2021-12, with the labels that each got.

#622 [1.58.0] Automatic upgrades
  content/release-notes/1.58.0.md
Labels: peer-review-done, type::docs

#623 Update backup-hooks.md
  content/vendor/snapshots/backup-hooks.md
Labels: peer-review-done, type::docs

#624 [1.58.1] Release notes
  content/release-notes/1.58.1.md
Labels: peer-review-done, type::docs

#626 [1.58.0] mention how to use the automatic updates feature
  content/release-notes/1.58.0.md
Labels: peer-review-done

#627 Update dashboard-graphs.md
  content/vendor/config/dashboard-graphs.md
Labels: type::docs

#631 add deploy version label flag to upstream upgrade cmd
  content/kots-cli/upstream.md
Labels: peer-review-done

#630 helm processing info
  .github/workflows/update-release-notes.yaml
  content/vendor/helm/helm-processing.md
  static/images/native-helm-base.png
  static/images/native-helm-downstream.png
  static/images/native-helm-midstream.png
Labels: peer-review-done, type::docs

#633 add the '--decrypt' flag to 'kubectl kots get config' docs
  content/kots-cli/get/config.md
Labels: peer-review-done, type::docs

#637 Release Notes 1.59.0
  content/release-notes/1.18.0.md
  content/release-notes/1.59.0.md
Labels: peer-review-done, type::docs

#636 [ 1.59.0 ] feat: remove minio requirements
  content/kotsadm/installing/stateful-components.md
Labels: peer-review-done, type::docs

#625 [1.59.0] add docs for 'get config'
  content/kots-cli/get/config.md
  content/kots-cli/get/restores.md
Labels: type::feature, peer-review-done, type::docs

#639 [1.59.1] Release notes
  content/release-notes/1.59.1.md
Labels: peer-review-done
