Repository replicatedhq/kots.io, pull requests merged in 2021-11, with the labels that each got.

#599 fix link to helmchart kind
  content/vendor/helm/helm-applications.md
Labels: peer-review-done

#596 native helm chart ordering
  content/vendor/native-helm/helm-charts-install-ordering.md
Labels: type::enhancement, peer-review-done

#600 Update airgapped-existing-cluster.md
  content/vendor/guides/airgapped-existing-cluster.md
Labels: peer-review-done

#601 Fix typo
  content/vendor/config/dashboard-buttons.md
Labels: peer-review-done

#603 Removed imaginary annotation called 'kots.io/include': and replaced it with 'kots.io/when'
  content/vendor/packaging/include-resources.md
Labels: peer-review-done

#604 Kots Release 1.56.0
  content/release-notes/1.56.0.md
Labels: peer-review-done

#607 fix: clarify ephemeral behavior of ConfigItem defaults
  content/reference/v1beta1/config.md
  content/vendor/packaging/template-functions.md
Labels: peer-review-done

#608 fix: add kustomize rollback to 1.56.0 rn
  content/release-notes/1.56.0.md
Labels: peer-review-done

#613 [1.57.0] feat(cli): add strict-security-context flag
  content/kots-cli/admin-console/upgrade.md
  content/kots-cli/install.md
Labels: peer-review-done

#614 [v1.?] feat(cli): added minimal-rbac flags for generate-manifest
  content/kots-cli/admin-console/generate-manifests.md
Labels: documentation, peer-review-done

#602 differentiate replicated and native helm documentation
  content/kotsadm/installing/helm-chart.md
  content/reference/v1beta1/helmchart.md
  content/release-notes/1.33.0.md
  content/release-notes/1.47.1.md
  content/release-notes/1.50.2.md
  content/vendor/helm/_index.md
  content/vendor/helm/chart-components.md
  content/vendor/helm/helm-airgap-builder.md
  content/vendor/helm/helm-applications.md
  content/vendor/helm/helm-charts-install-ordering.md
  content/vendor/helm/helm-processing.md
  content/vendor/helm/optional-charts.md
  content/vendor/helm/optional-value-keys.md
  content/vendor/helm/overview.md
  content/vendor/helm/using-native-helm-charts.md
  content/vendor/helm/using-replicated-helm-charts.md
  content/vendor/native-helm/_index.md
  content/vendor/packaging/packaging-an-app.md
Labels: documentation, peer-review-done

#597 Changed response to request and minor formatting
  content/vendor/entitlements/creating-entitlements.md
Labels: peer-review-done

#616 Make style match previous notes
  content/release-notes/1.57.0.md
Labels: peer-review-done
