Repository replicatedhq/kots.io, pull requests merged in 2022-03, with the labels that each got.

#687 Update semver docs and mention default behavior
  content/vendor/packaging/promoting-releases.md
Labels: type::docs, team::orange

#690 New channels disable semver by default and update semver toggle text
  content/vendor/packaging/promoting-releases.md
Labels: type::docs, team::orange

#693 Clarify how non-semvers are sorted
  content/vendor/packaging/promoting-releases.md
Labels: type::docs, team::orange

#617 Changed the Helm version and removed BETA
  content/kots-cli/pull.md
  content/reference/v1beta1/helmchart.md
Labels: peer-review-needed, type::docs

#695 add deprecated banner
  themes/hugo-whisper-theme/assets/scss/pages/_home.scss
  themes/hugo-whisper-theme/layouts/_default/baseof.html
  themes/hugo-whisper-theme/layouts/partials/new-docs-banner.html
Labels: type::feature, team::blue

#689 [1.66.0] Add --exclude-apps, --exclude-admin-console, and --wait-for-apps flags to 'kots restore' command
  content/kots-cli/restore/_index.md
  content/release-notes/1.47.0.md
Labels: type::feature, type::docs, team::orange

#698 Adds guidance for where to update kots docs
  README.md
Labels: type::docs

#700 Add page for all release notes
  .gitignore
  content/all-release-notes/_index.md
  gen-release-notes-pdf.sh
  themes/hugo-whisper-theme/layouts/partials/sidebar.html
  themes/hugo-whisper-theme/layouts/section/all-release-notes.html
Labels: type::feature, team::blue

#703 more doc link updates
  config.yaml
  themes/hugo-whisper-theme/assets/js/scripts.js
  themes/hugo-whisper-theme/assets/scss/pages/_home.scss
  themes/hugo-whisper-theme/layouts/index.html
  themes/hugo-whisper-theme/layouts/partials/main-menu.html
  themes/hugo-whisper-theme/layouts/partials/new-docs-banner.html
  themes/hugo-whisper-theme/layouts/partials/sub-footer.html
  themes/hugo-whisper-theme/layouts/partials/suite-banner.html
  themes/hugo-whisper-theme/layouts/section/all-release-notes.html
Labels: type::feature, team::blue

#704 link to internal headers in PDF
  themes/hugo-whisper-theme/layouts/section/all-release-notes.html
Labels: type::feature, type::docs, team::blue
