Repository replicatedhq/kots.io, pull requests merged in 2022-02, with the labels that each got.

#658 Release notes v1.61.0
  content/kots-cli/get/versions.md
  content/kotsadm/snapshots/basic-install/_index.md
  content/kotsadm/snapshots/disaster-recovery.md
  content/kotsadm/snapshots/restic-troubleshooting/_index.md
  content/kotsadm/snapshots/restic/_index.md
  content/kotsadm/snapshots/restore.md
  content/kotsadm/snapshots/storage-destinations.md
  content/kotsadm/snapshots/supported-providers/_index.md
  content/kotsadm/snapshots/troubleshooting.md
  content/kotsadm/snapshots/velero-troubleshooting/_index.md
  content/kotsadm/snapshots/velero/_index.md
  content/reference/v1beta1/_index.md
  content/reference/v1beta1/backup.md
  content/release-notes/1.15.0.md
  content/release-notes/1.23.1.md
  content/release-notes/1.61.0.md
  content/vendor/guides/configuring-application-snapshots.md
  content/vendor/snapshots/backup-hooks.md
  content/vendor/snapshots/overview.md
  netlify.toml
Labels: peer-review-done, type::docs

#657 add k8s 1.23
  content/kotsadm/installing/system-requirements.md
  hack/release-notes.md.tmpl
Labels: peer-review-done, type::docs, team::orange

#660 Update 1.61.0.md
  content/release-notes/1.61.0.md
Labels: peer-review-needed, type::docs

#661 builder is ONLY for determining images
  content/vendor/helm/helm-airgap-builder.md
Labels: peer-review-needed, type::docs

#662 [1.62.0] Target/Minimum KOTS version reference docs
  content/reference/v1beta1/application.md
Labels: peer-review-done, type::docs, team::orange

#664 [1.62.0] release notes
  content/release-notes/1.62.0.md
Labels: peer-review-done, type::docs

#668 Update private-images.md
  content/vendor/packaging/private-images.md
Labels: peer-review-needed, type::docs

#669 Add limitations for minKotsVersion
  content/reference/v1beta1/application.md
Labels: peer-review-needed, type::docs, team::orange

#663 update docs to reflect new default behavior for kots get config
  content/kots-cli/get/config.md
Labels: peer-review-needed, type::docs, team::orange

#671 [v1.63.0] Adds release notes for kots
  content/release-notes/1.63.0.md
Labels: peer-review-needed, type::docs, team::blue

#666 [1.63.0] kots upstream upgrade --wait flag reference docs
  content/kots-cli/upstream.md
Labels: type::docs, team::orange

#632 Update helm-processing.md
  content/vendor/guides/configuring-application-snapshots.md
  content/vendor/helm/helm-processing.md
Labels: type::docs

#672 Add kubectl 1.23.x
  content/reference/v1beta1/application.md
Labels: type::docs, team::orange

#656 feat: add versioned kots install url
  content/kots-cli/getting-started.md
  content/vendor/guides/existing-cluster.md
Labels: peer-review-done, type::docs, team::orange

#674 Update _index.md
  content/kots-cli/get/_index.md
  content/kots-cli/get/versions.md
Labels: peer-review-needed, type::docs

#676 Say which KOTS version introed min and target KOTS version
  content/reference/v1beta1/application.md
Labels: peer-review-needed, type::docs, team::orange

#680 updated install docs for new --no-port-forward flag
  content/kots-cli/install.md
Labels: peer-review-needed, type::docs, team::orange

#681 updating and deleting licenses info
  content/vendor/entitlements/creating-entitlements.md
Labels: type::docs

#682 release notes for kots 1.65.0
  content/release-notes/1.65.0.md
Labels: peer-review-needed, type::docs, team::blue

#677 [1.65.0] Kots upstream download CLI command docs
  content/kots-cli/upstream.md
  content/kots-cli/upstream/_index.md
  content/kots-cli/upstream/download.md
  content/kots-cli/upstream/upgrade.md
  content/reference/v1beta1/application.md
  content/release-notes/1.17.0.md
  content/release-notes/1.18.0.md
  content/release-notes/1.19.0.md
  content/release-notes/1.20.0.md
  content/release-notes/1.25.0.md
  content/release-notes/1.29.0.md
  content/release-notes/1.30.0.md
  content/release-notes/1.38.0.md
  content/release-notes/1.43.1.md
  content/release-notes/1.49.0.md
  content/release-notes/1.59.0.md
  content/release-notes/1.59.1.md
  content/release-notes/1.63.0.md
Labels: peer-review-needed, type::docs, team::orange

#684 Add missing release notes
  content/release-notes/1.65.0.md
Labels: peer-review-done, type::docs, team::orange

#675 Remove minKotsVersion limitations
  content/reference/v1beta1/application.md
Labels: peer-review-needed, type::docs, team::orange

#679 add documentation for the 2 new commands
  content/vendor/cli/channel disable-semantic-versioning.md
  content/vendor/cli/channel enable-semantic-versioning.md
Labels: peer-review-done, type::docs, team::orange

#688 Change API version for ingress
  content/reference/template-functions/identity-context.md
  content/vendor/packaging/include-resources.md
  content/vendor/packaging/ingress.md
  content/vendor/packaging/using-tls-certs.md
Labels: type::docs, team::orange
