Repository replicatedhq/kots.io, pull requests merged in 2022-01, with the labels that each got.

#640 Remove extraneous quotation mark
  content/release-notes/1.59.1.md
Labels: peer-review-done

#642 Update helm-processing.md
  content/vendor/helm/helm-processing.md
Labels: peer-review-done, type::docs

#609 SH33414: Updated screenshots for Admin Console GitOps
  content/kotsadm/gitops/multi-app-workflows.md
  content/kotsadm/gitops/single-app-workflows.md
  static/images/2021-11-11_09-37-15.png
  static/images/gitops-action-new-multi.png
  static/images/gitops-action.png
  static/images/gitops-apps.png
  static/images/gitops-connected-multi-app.png
  static/images/gitops-connected-multi.png
  static/images/gitops-connected-single-app.png
  static/images/gitops-connected.png
  static/images/gitops-no-connection-multi-app.png
  static/images/gitops-no-connection-single-app.png
  static/images/gitops-no-connection.png
  static/images/gitops-provider-multi-app.png
  static/images/gitops-provider.png
  static/images/gitops-settings-multi-app.png
  static/images/gitops.png
Labels: type::feature, peer-review-needed

#643 feat(rn): release notes v1.59.2
  content/release-notes/1.59.2.md
Labels: peer-review-needed

#641 Typo
  content/reference/v1beta1/config.md
Labels: type::bug, bug::normal

#644 41650: Fixing broken links to images
  content/kotsadm/gitops/multi-app-workflows.md
  content/kotsadm/gitops/single-app-workflows.md
Labels: peer-review-done, type::docs

#648 Update stated K8s support
  content/kotsadm/installing/system-requirements.md
Labels: peer-review-done, type::docs

#635 document the port number used for the admin-console command
  content/kots-cli/admin-console/_index.md
Labels: peer-review-done

#651 update time for release notes
  content/release-notes/1.59.3.md
Labels: type::chore, release-notes

#650 Updated kubectl versions
  content/reference/v1beta1/application.md
Labels: type::chore

#652 Use present tense
  content/release-notes/1.59.3.md
Labels: peer-review-done, type::docs

#653 Update Kubernetes supported versions
  content/kotsadm/installing/system-requirements.md
Labels: type::docs

#646 41189 Updates screenshots
  content/vendor/entitlements/community-licenses.md
  content/vendor/guides/airgapped-cluster.md
  content/vendor/guides/ha-guide.md
  content/vendor/guides/persistent-datastores.md
  static/images/community-license-bundle.png
  static/images/community-license-dashboard.png
  static/images/edit-patches-kots-app.png
  static/images/guides/kots/airgap-automatic-builds.png
  static/images/guides/kots/airgap-build-bundle.png
  static/images/guides/kots/airgap-channels.png
  static/images/guides/kots/airgap-customers.png
  static/images/guides/kots/airgap-download-bundle.png
  static/images/guides/kots/airgap-download-license.png
  static/images/guides/kots/airgap-upload-bundle.png
  static/images/guides/kots/airgap-upload-deploy.png
  static/images/guides/kots/airgap-upload-new-version.png
  static/images/guides/kots/database-config.png
  static/images/guides/kots/deploy-config-change.png
  static/images/guides/kots/embedded-pg-deployed.png
  static/images/guides/kots/external-pg-config-fake.png
  static/images/guides/kots/ha-cluster-app-deployed.png
  static/images/guides/kots/ha-cluster-app-dployed.png
  static/images/guides/kots/ha-cluster-cluster-mgmt.png
  static/images/guides/kots/helm-chart-check-for-updates-1.png
  static/images/guides/kots/helm-chart-check-for-updates-2.png
  static/images/guides/kots/helm-chart-grafana-config-screen.png
  static/images/guides/kots/pg-consumer-deployed.png
  static/images/guides/kots/real-postgres-values.png
  static/images/guides/kots/view-update-2.png
  static/images/guides/kots/view-update.png
  static/images/kotsadm-dashboard-configureprometheus.png
  static/images/kotsadm-dashboard-graph.png
  static/images/kustomize-view-history-deploy.png
Labels: peer-review-done, type::docs

#645 41189-JQ: Update screenshots for Admin Console in kots.io docs
  content/kotsadm/updating/updating-kots-apps.md
  content/vendor/guides/cli-quickstart.md
  content/vendor/guides/configuring-application-snapshots.md
  content/vendor/guides/existing-cluster.md
  content/vendor/guides/quickstart.md
  content/vendor/guides/using-ecr-private-images.md
  static/images/diff-releases.png
  static/images/guides/kots/application.png
  static/images/guides/kots/configuration.png
  static/images/guides/kots/priv-reg-ecr-version-history.png
  static/images/guides/kots/snap_guide_detail_snap.png
  static/images/guides/kots/snap_guide_snap_list_v.png
  static/images/guides/kots/snap_guide_storage_conf.png
  static/images/guides/kots/view-update.png
  static/images/kotsadm-dashboard-appstatus.png
  static/images/new-changes.png
  static/images/new-version-available-old.png
  static/images/new-version-available.png
  static/images/preflight-checks.png
  static/images/version-history.png
Labels: peer-review-done, type::docs
